MTP-1677 Guide mobile chaptermenu with link, fix zindex bug + scroll …
Mattilsynet/designsystem pull request #1003
Opened 2023-12-28 13:26 UTC by petterkoding

work in progress

also fixes:

hides scrollbar gutter if theres no overflow, zindex issues with breadcrumbs and dialogue box overlapping mobile menu

2024-01-11 07:03 UTC, lha047 commented on mt-kit/core/css/src/components/_chapter-menu.scss
> +    padding: var(--spacer-xx-small) 0;
Why change this?

2024-01-11 07:05 UTC, lha047 commented on mt-kit/core/css/src/components/_chapter-menu.scss
> +      border-bottom: none;
Dont think you need this. The border bottom is on the list item

2024-01-11 07:13 UTC, lha047 commented on mt-kit/core/css/src/components/_chapter-menu.scss
> +    border-bottom: none;
Cool that you have looked into `:has()`. Just be aware that it doesnt work in older bowsers. In this case I it doesnt have that much of an impact. The older browsers will get the extra border bottom. Just be carefull when using new features and make sure it works for older browsers too

2024-01-11 07:19 UTC, lha047 commented
Looks like the meny is sticky when you dont have JS. It has to behave as it used to when there is no JS. This implementation hides all the content as the menu always cover the entire page and you are not able to remove it

2024-01-11 07:22 UTC, lha047 commented on mt-kit/core/css/src/components/_layout-with-sidebar.scss
> +    p {
Do you need this? I cant see where it is used

2024-01-11 07:25 UTC, lha047 commented on mt-kit/core/css/src/components/_layout-with-sidebar.scss
> +    p {
Is this for styling what is in [aria-expanded='false']?

2024-01-11 07:26 UTC, lha047 commented on mt-kit/core/css/src/components/_layout-with-sidebar.scss
> +      color: var(--color-primary);
Same as above. Cant see a p-tag inside the expanded

2024-01-11 07:48 UTC, lha047 commented
<img width="429" alt="Screenshot 2024-01-11 at 08 47 59" src="https://github.com/Mattilsynet/designsystem/assets/1166832/0b205bd5-ee3c-456d-9f55-18077bb26d64">
The link have to have focus styling

2024-01-11 07:56 UTC, lha047 commented
<img width="780" alt="Screenshot 2024-01-11 at 08 54 56" src="https://github.com/Mattilsynet/designsystem/assets/1166832/e4a936c8-9655-4da6-81a5-641ec3c2fc75">
Can you fix the width and height of the close button on desktop? Should be the minimum width and height

2024-01-11 08:04 UTC, lha047 commented on mt-kit/core/css/src/components/_layout-with-sidebar.scss
> +    a {
Style on the class

2024-01-11 08:12 UTC, lha047 commented on mt-kit/core/css/src/utilities/_layout.scss
> +.responsive-show-flex-column-xx-large {
Dont think you need this. We should show the link on desktop as well to be consistent

2024-01-11 08:14 UTC, lha047 requested changes
Good work
See comments. Make sure it works without JS as well.
Just ask if something is unclear

2024-01-11 13:22 UTC, petterkoding commented on mt-kit/core/css/src/components/_chapter-menu.scss
> +    padding: var(--spacer-xx-small) 0;
This was to compensate for the "Veileder:" text above the title link. Looking at the figma design, it had more spacing above and under, but since its no longer applicable I´ll change back

2024-01-11 13:23 UTC, petterkoding commented on mt-kit/core/css/src/components/_chapter-menu.scss
> +    border-bottom: none;
Was afraid of that, too bad it isn´t fully supported yet.

2024-01-15 06:28 UTC, lha047 requested changes
Can you update the storybook Guide story so we can see how it works only in storybook

2024-01-15 08:08 UTC, lha047 commented on mt-kit/core/css/src/components/_chapter-menu.scss
> +      .layout-flex {
I would add `.mt-li` to the list item and then use `.mt-li` for this styling. It doesnt seem right to use the `.layout-flex` for this kind of styling as it is a styling for the list item (and layout-flex can be for other things than list items)

2024-01-15 08:10 UTC, lha047 commented on mt-kit/core/css/src/components/_layout-with-sidebar.scss
> +    .aside-header {
Do you need this? The css is mobile first and should keep the display: none styling you added on line 19 until you use some other value for `display` in a media query for a larger size.

2024-01-22 07:17 UTC, lha047 requested changes
Update the Guide story

2024-01-22 07:25 UTC, lha047 commented
![Screenshot 2024-01-22 at 08 24 53](https://github.com/Mattilsynet/designsystem/assets/1166832/2bbdc08b-6353-48b2-8024-3be955476239)
Search link layout is broken

2024-01-22 07:28 UTC, lha047 commented on mt-kit/core/css/src/components/_layout-with-sidebar.scss
> +        //.mobile-menu {
REmove comment

2024-01-22 07:31 UTC, lha047 commented on mt-kit/core/css/src/components/_layout-with-sidebar.scss
> +    width: 75%;
I would create variables for the width here and the one with 25%. Place them underneath each other so it is easy to see what this is.

2024-02-26 11:25 UTC, lha047 requested changes
![Screenshot 2024-02-26 at 09 28 49](https://github.com/Mattilsynet/designsystem/assets/1166832/a7ff8ae0-de72-45af-96c6-53cc3bb0805e)
Can you fix the color of the x-button

2024-02-28 08:36 UTC, merged