MTP-1958 mtp-1904 Newsletter form hover and checkbox issues
Mattilsynet/designsystem pull request #1047
Opened 2024-02-15 09:59 UTC by petterkoding

Fix for hovering on Newsletter disclosures in firefox, MTP-1958
and checkboxes getting squashed by long texts, MTP-1904

2024-02-26 11:23 UTC, lha047 requested changes
See comments :)

2024-02-26 11:23 UTC, lha047 commented on mt-kit/core/css/src/utilities/_layout.scss
> +  flex-wrap: nowrap;
This is going to change it for all the layout-flex-col. Did you check that it doesnt break any thing? Suggest you make a new class with this addition

2024-02-26 11:23 UTC, lha047 commented on mt-kit/core/css/src/components/_radio-checkbox.scss
> +  flex-shrink: 0;
Suggest you make a class for this in layout and use that. This class should not consider it self with layout based on parent

2024-03-04 15:16 UTC, petterkoding commented on mt-kit/core/css/src/components/_radio-checkbox.scss
> +  flex-shrink: 0;
appears that its no longer needed after using  `flex-wrap: nowrap` on the parent fieldset and on the nested fieldsets as well.

2024-03-06 07:41 UTC, lha047 requested changes
<img width="774" alt="Screenshot 2024-03-06 at 07 53 40" src="https://github.com/Mattilsynet/designsystem/assets/1166832/6bf2d5fe-dcf2-4cd7-b823-8650a8ed655e">
<img width="774" alt="Screenshot 2024-03-06 at 07 53 30" src="https://github.com/Mattilsynet/designsystem/assets/1166832/2e63a56c-2ac8-4135-aea5-0c27c896c662">

Still breaks. Update stories to show how it breaks with long sentences in checkbox labels
Look into how the `.form-control` works with the grid. It should work with the correct values. You should not need the flex no-wrap. Check the html classes on checkboxwith subsets. Look into the displays in _checkboxes-with-subsets

2024-03-22 07:49 UTC, amundlindstol approved these changes
LGTM :D

2024-03-22 08:50 UTC, merged