MTP-2178 adjust header for mobile
Mattilsynet/designsystem pull request #1064
Opened 2024-03-15 12:56 UTC by petterkoding

- add slightly larger search icon
- align items in header
- make logo smaller on mobile

logo is passed to Dropdown component in Web

see:  https://github.com/Mattilsynet/mattilsynet-web/pull/843

2024-03-20 07:01 UTC, lha047 requested changes
Have a look at comments. 

Could you also fix the no-js styling?
<img width="1366" alt="Screenshot 2024-03-20 at 07 53 39" src="https://github.com/Mattilsynet/designsystem/assets/1166832/fcb2bd61-cb44-40b6-a9e4-08fa2305a89b">

2024-03-20 07:01 UTC, lha047 commented on mt-kit/core/css/src/utilities/_layout.scss
> +  >.mt-link {
Can you update the headers in the stories so we can see how this works?

2024-03-21 07:27 UTC, lha047 requested changes
Good work :)

Did you look at the styling of the header without JS?

2024-03-21 09:51 UTC, petterkoding commented
> Good work :)
> 
> Did you look at the styling of the header without JS?

See the other PR for styling without JS

2024-03-21 12:57 UTC, lha047 approved these changes
👍

2024-03-22 08:08 UTC, merged