MTP-2171 new pagination component #minor
Mattilsynet/designsystem pull request #1068
Opened 2024-03-21 07:18 UTC by lha047

2024-03-21 07:52 UTC, amundlindstol commented on mt-kit/core/svelte/src/lib/svelte/components/pagination/Pagination.svelte
> +  $: media = undefined
seems like you only use media for media?.matches.
Could you create a bool var with a better name?

2024-03-21 08:04 UTC, amundlindstol requested changes
When navigating on desktop, the numbers "jump" when going from 2 to 3
![image](https://github.com/Mattilsynet/designsystem/assets/21691168/13a847a2-ce36-44b0-b60b-ca8f9fe33f97)
![image](https://github.com/Mattilsynet/designsystem/assets/21691168/93810985-95f9-48dc-b05a-fd70df840e2e)
I would prefer if the current page only moves one step at the time.

Also, there's room to have every number 1 through 7 displayed without any truncate.

This should not happen, right?
![image](https://github.com/Mattilsynet/designsystem/assets/21691168/6ec9ae7a-7e34-4a68-b419-b107fe772935)

2024-03-22 13:24 UTC, petterkoding requested changes
nice work! Works smoothly. Take a look at label for screenreaders

2024-03-22 13:24 UTC, petterkoding commented on mt-kit/core/svelte/src/lib/svelte/components/pagination/Pagination.svelte
> +              <span class="inclusively-hidden-initial">{labelPage}</span>
Screenreaders wont notify if its the last page which may disorient users. I suggest changing to "page x of y" as discussed

2024-03-22 13:47 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/components/pagination/Pagination.svelte
> +              <span class="inclusively-hidden-initial">{labelPage}</span>
Fixed

2024-03-22 13:49 UTC, amundlindstol approved these changes
LGTM :D

2024-03-22 13:51 UTC, merged