MTP-2182 fadein-out overlay
Mattilsynet/designsystem pull request #1071
Opened 2024-03-21 19:00 UTC by petterkoding

2024-04-11 12:30 UTC, lha047 commented on mt-kit/core/css/src/components/_dropdown.scss
> +      transition: background 0.7s cubic-bezier(.38,.02,.26,1.01);
Create variable for the cubic-function and the duration

2024-04-11 12:30 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/components/Dropdown.svelte
> +        <div in:slide={{ duration: 2200 }}>
2200 is a bit long?

2024-04-12 08:01 UTC, petterkoding commented on mt-kit/core/svelte/src/lib/svelte/components/Dropdown.svelte
> +        <div in:slide={{ duration: 2200 }}>
changed it to 900 and added out:slide for dismount transition

2024-04-15 14:08 UTC, lha047 commented on mt-kit/core/css/src/components/_dropdown.scss
>        .dropdown-content {
Do you need this when there is nothing inside?

2024-04-15 14:14 UTC, lha047 requested changes
Nice :D 

See comments

2024-04-15 14:14 UTC, lha047 commented on mt-kit/core/css/src/components/_dropdown.scss
> +      > * {
Dont think you need this as this should be on the content of the slot

2024-04-16 05:40 UTC, lha047 approved these changes
Good job :D

2024-04-18 07:47 UTC, merged