MT-553 Change hard coded phrase (x tegn igjen) to dynamic
Mattilsynet/designsystem pull request #109
Opened 2021-12-01 12:00 UTC by itemodahl

MT-553

2021-12-01 12:53 UTC, tajakobsen requested changes
Looks good. I just have a few small tings that can be good to consider.

2021-12-01 12:53 UTC, tajakobsen commented on src/svelte/form/TextArea.svelte
> +  export let countCharactersLeftLabel: string;
We still allows `undefined` as a legal value here, since we provide a default value in  `countCharacters`, right?

```suggestion
  export let countCharactersLeftLabel: string | undefined;
```

2021-12-01 12:53 UTC, tajakobsen commented on src/ts/count-characters.ts
> +  countCharactersLeftLabel: string = 'tegn igjen'
Since we can only have one parameter as input to an action, I think it would be most future proof to let it be an object, with the value inside it. That way it can be expanded with more parameters later.

This same principle goes for custom events too.

```suggestion
  parameters: { countCharactersLeftLabel: string } = {countCharactersLeftLabel: 'tegn igjen'}
```

2021-12-01 13:14 UTC, itemodahl commented on src/ts/count-characters.ts
> +  countCharactersLeftLabel: string = 'tegn igjen'
Agree. Changing it now.

2021-12-01 13:45 UTC, tajakobsen requested changes
The preview in storybook is broken. I have suggested what in a comment what the fix is.

Also `countCharacters` is also used by `TextInput.svelte`, so it should also be updated with this change.

2021-12-01 13:45 UTC, tajakobsen commented on src/svelte/form/TextArea.svelte
> +  use:countCharacters={countCharactersLeftLabel}
You are not wrapping the string in an object, while `countCharacters` expects an object.

2021-12-01 13:45 UTC, tajakobsen commented on src/ts/count-characters.ts
> +  params: {countCharactersLeftLabel: string} = {countCharactersLeftLabel: 'tegn igjen'}
Use "TextArea with error" to check the fallback case (`'tegn igjen'`).

2021-12-08 07:55 UTC, lha047 commented on stories/components/form/TextArea.stories.svelte
> +    countCharactersLeftLabel: 'Karakterer igjen'
```suggestion
    countCharactersLeftLabel: 'karakterer igjen'
```

2021-12-08 09:26 UTC, tajakobsen approved these changes
Looks good! Good job.

2021-12-08 10:06 UTC, merged