MTP-2407 fremhevet innhold endringer
Mattilsynet/designsystem pull request #1109
Opened 2024-07-09 07:55 UTC by petterkoding

added $transition-ms-... variables to use for smoother background-color transitions

2024-07-09 08:13 UTC, lha047 requested changes
You need to update all variations of fremhevet innhold. 
Should it have the big border radius? See comment

2024-07-09 08:13 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
> +    &.b-r-radius {
There is already a class that does this. `.box-border-radius-br-l`

2024-07-09 08:22 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
> +    &.b-r-radius {
will change and delete the class i created

2024-07-10 07:09 UTC, lha047 approved these changes
Good work :D

2024-07-10 07:56 UTC, merged