MTP-2394 forsidekort klikkbare, nye farger, fix test
Mattilsynet/designsystem pull request #1111
Opened 2024-07-11 08:38 UTC by petterkoding

2024-07-12 07:21 UTC, lha047 requested changes
Looks good. Could you make the state effects reuseable?

2024-07-12 07:21 UTC, lha047 commented on mt-kit/core/css/src/components/_menu-points.scss
> +  &:hover {
The hover and active states seems to repeat. Could you make the code reusable?

2024-08-02 07:33 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.svelte
> +        <p class="mt-{headerTag}">
Maybe we should have header-tag on the titles here

2024-08-02 07:41 UTC, lha047 requested changes
Good job. See comments

2024-08-02 07:41 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.svelte
> +        <p class="mt-{headerTag}">
Maybe add and extra class here so you can target it without listing all the possible header tag? The css will currently not apply for all the possible header-tag options

2024-08-02 10:20 UTC, petterkoding commented on mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.svelte
> +        <p class="mt-{headerTag}">
<h3 class="mt-{headerTag} menu-point-heading"> ?

2024-08-05 05:07 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.svelte
> +        <p class="mt-{headerTag}">
Yes 👍

2024-08-05 08:40 UTC, petterkoding commented on mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.svelte
> +        <p class="mt-{headerTag}">
fixed

2024-08-08 09:12 UTC, petterkoding commented on mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.svelte
> +        <h3 class="mt-{headerTag} menu-point-heading">
use HeadingLevel

2024-08-08 12:28 UTC, lha047 requested changes

2024-08-08 12:28 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.svelte
> +        <HeadingLevel class="menu-point-heading" headingLevel={+headerTag.charAt(1)}
Pass mt-h3 for same styling independant of tag

2024-08-08 14:34 UTC, lha047 approved these changes
Nice :D

2024-08-09 06:23 UTC, merged