MTP-2397 text Link component, rel external styling, stories
Mattilsynet/designsystem pull request #1112
Opened 2024-07-12 10:44 UTC by petterkoding

wip

2024-07-29 07:52 UTC, amundlindstol commented on mt-kit/core/css/src/global/_links.scss
> +  color: var(--color-text);
Keep color-links and change color

2024-07-29 07:52 UTC, amundlindstol commented on mt-kit/core/css/src/global/_links.scss
> +p:has(a.is-external) .mt-link.is-external {
move to typography

2024-07-31 07:06 UTC, lha047 commented on mt-kit/core/css/src/_theme.scss
> +$link-underline-color: var(--color-mt-havdyp);
Try to stick to the naming patterns. Would call it color-link-underline

2024-07-31 07:38 UTC, lha047 requested changes
I dont think this design has good enough accessibility. Will discuss with designers.
Setting request changes for now

2024-07-31 07:38 UTC, lha047 commented on mt-kit/core/svelte/src/stories/Links.stories.svelte
> +    max-width: 680px;
use rem

2024-08-08 09:51 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
> +      margin-right: var(--spacer-xxx-small);
use mixin

2024-08-08 09:51 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
> +    text-decoration: $color-link-underline underline $border-width-medium;
try shorthand

2024-08-08 09:51 UTC, lha047 requested changes

2024-08-08 09:51 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
> +      content: var(--icon-pdf);
Use mixin

2024-08-08 09:51 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
>        content: var(--icon-document);
use mixin

2024-08-08 09:51 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
> +      content: var(--icon-carret-left);
use mixin

2024-08-08 09:51 UTC, lha047 commented on mt-kit/core/svelte/src/lib/ts/utils.ts
> +export function isExternalLink(href: string): boolean {
remove?

2024-08-08 10:36 UTC, petterkoding commented on mt-kit/core/svelte/src/lib/ts/utils.ts
> +export function isExternalLink(href: string): boolean {
removed because its not in use

2024-08-08 10:36 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
> +      content: var(--icon-carret-left);
fixed

2024-08-08 10:36 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
>        content: var(--icon-document);
fixed

2024-08-08 10:36 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
> +      content: var(--icon-pdf);
fixed

2024-08-08 10:36 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
> +    text-decoration: $color-link-underline underline $border-width-medium;
`text-decoration-thickness` worked

2024-08-08 10:44 UTC, lha047 approved these changes
Nice :D

2024-08-08 10:45 UTC, merged