MTP 2395 transport link endringer
Mattilsynet/designsystem pull request #1113
Opened 2024-07-15 12:20 UTC by petterkoding

transport link styling
default
primary
primary--large
secondary
secondary--large

WIP

2024-08-01 10:28 UTC, lha047 requested changes
See comments

2024-08-01 10:28 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
>      &--primary {
For reuse I would create variables for default, hover and active and use in the &--primary and &-large. Same for the states in secondary. Maybe include variation and state in the names

2024-08-01 10:28 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
> -        @extend .no-underline;
Missing border radius
![Screenshot 2024-08-01 at 12 11 40](https://github.com/user-attachments/assets/8b9ec2f4-eb35-484b-9efd-ac2ee4c5cd7e)

2024-08-01 10:28 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
> -    --transportlink-background: var(--color-#{$transportlink-default-color});
Missing underline and state styling
![Screenshot 2024-08-01 at 12 11 48](https://github.com/user-attachments/assets/218d9b7f-9da8-48bc-9893-f1bd242754cb)

2024-08-01 10:30 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
> -        color: var(--mt-button-primary-color-hover);
Why not use the mixins?

2024-08-05 09:02 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
> -    --transportlink-background: var(--color-#{$transportlink-default-color});
the default and `--primary` and `--secondary` (not large versions) will inherit text-decoration from the `.mt-link` class. Adjusting it thereafter by removing on hover (default) and setting to `none` on --primary and --secondary.

2024-08-05 11:54 UTC, lha047 requested changes
![Screenshot 2024-08-05 at 13 53 27](https://github.com/user-attachments/assets/1d9f95c1-e55c-422d-a6a5-e9619361c378)
Looks like you need som gaps after you removed margin on the psudo

2024-08-08 09:27 UTC, petterkoding commented on mt-kit/core/css/src/utilities/colors.js
> +    color: '#9BCAB9',
make global vars for new link colors

2024-08-08 11:30 UTC, lha047 approved these changes
👍

2024-08-08 11:56 UTC, merged