MTP-2406 lenkeliste
Mattilsynet/designsystem pull request #1116
Opened 2024-07-16 08:21 UTC by petterkoding

2024-08-01 11:10 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
>    &.forward-arrow-end-link {
If we're not having any links with arrows after. Maybe remove the classes with "end" and update?

2024-08-02 06:59 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
>    &.forward-arrow-end-link {
Figma has these examples though

2024-08-02 07:45 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
>    &.forward-arrow-end-link {
ok

2024-08-02 07:49 UTC, lha047 requested changes
See comment

2024-08-02 07:49 UTC, lha047 commented on mt-kit/core/svelte/src/stories/Links.stories.svelte
> +          <Link href={link.href} class="forward-arrow" linkText={link.text} />
![Screenshot 2024-08-02 at 09 46 56](https://github.com/user-attachments/assets/fb8c5fce-1bd2-4a7e-8766-27da5eca07b6)
Shouldnt the hover effect be the slightly larger underline?

2024-08-02 07:54 UTC, lha047 approved these changes
👍 looks like it will be ok when the general link styling is applied

2024-08-02 07:57 UTC, petterkoding commented on mt-kit/core/svelte/src/stories/Links.stories.svelte
> +          <Link href={link.href} class="forward-arrow" linkText={link.text} />
MTP-2397 will fix it

2024-08-02 07:57 UTC, merged