MTP-2398 refac logic for external links, add xp, mailto, tel
Mattilsynet/designsystem pull request #1125
Opened 2024-08-09 08:39 UTC by petterkoding

2024-08-12 08:30 UTC, amundlindstol commented on mt-kit/core/css/src/utilities/_mixins.scss
> +    display: flex;
can you confirm that the single links are not wider than usual? :)

2024-08-12 08:50 UTC, petterkoding commented on mt-kit/core/css/src/utilities/_mixins.scss
> +    display: flex;
![image](https://github.com/user-attachments/assets/4b9ea4f4-69a5-4fa1-872e-2d157aba431c)

2024-08-12 08:56 UTC, petterkoding commented on mt-kit/core/css/src/utilities/_mixins.scss
> +    display: flex;
looks like they will keep their original width, however, found some other stuff that needs to be excluded. Links starting with '?' (params)

2024-08-12 13:00 UTC, petterkoding commented on mt-kit/core/css/src/utilities/_mixins.scss
> +    display: flex;
changed it to be default `inline-flex` cause it fits all use cases for now and wont mess with widths

2024-08-14 06:33 UTC, lha047 requested changes
<img width="755" alt="Screenshot 2024-08-14 at 08 25 14" src="https://github.com/user-attachments/assets/7472c0ac-83f4-4cdc-820a-84abc8ebe84b">
The links should break, following the text, when they are long

2024-08-14 06:33 UTC, lha047 commented on mt-kit/core/css/src/components/_status.scss
> +    :first-child:not(h2):not(h3):not(h4):not(a) {
Why do you need this on a?

2024-08-14 13:16 UTC, petterkoding commented on mt-kit/core/css/src/components/_status.scss
> +    :first-child:not(h2):not(h3):not(h4):not(a) {
Example in image wasnt ideal, reason was external links got margin-top added, but since changing to `display: inline` it wont be a problem anymore

2024-08-16 08:50 UTC, lha047 requested changes

2024-08-16 08:50 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
> +    @include apply-external-link-icon($position: after, $target-child: 'h2, h3') {
Dont need this here. This should be used for our content

2024-08-16 08:50 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
> +    @include apply-external-link-icon($position: after, $target-child: 'h2, h3') {
Dont need this here. This should be used for our content

2024-08-16 10:49 UTC, lha047 approved these changes
LGTM 👍

2024-08-16 10:52 UTC, merged