MTP-2459 Change link icons in Menu, update Story
Mattilsynet/designsystem pull request #1127
Opened 2024-08-13 08:09 UTC by petterkoding

2024-08-14 06:41 UTC, lha047 requested changes
<img width="763" alt="Screenshot 2024-08-14 at 08 41 21" src="https://github.com/user-attachments/assets/23521146-78d3-4487-bb1d-a66c5c9061f3">
Talk to Emilie about how they want it

2024-08-15 12:02 UTC, lha047 commented on mt-kit/core/css/src/utilities/_layout.scss
> +  .dropdown-content {
Dont think this is the right place to do this

2024-08-15 12:10 UTC, lha047 commented
<img width="1754" alt="Screenshot 2024-08-15 at 14 09 24" src="https://github.com/user-attachments/assets/e8fca337-290b-487c-9cc2-fa9e2ddc1233">
The hover effect looks wrong. Should find another solution

2024-08-15 12:56 UTC, petterkoding commented
> <img alt="Screenshot 2024-08-15 at 14 09 24" width="1754" src="https://private-user-images.githubusercontent.com/1166832/358213948-e8fca337-290b-487c-9cc2-fa9e2ddc1233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjY3ODksIm5iZiI6MTcyMzcyNjQ4OSwicGF0aCI6Ii8xMTY2ODMyLzM1ODIxMzk0OC1lOGZjYTMzNy0yOTBiLTQ4N2MtOWNjMi1mYTllMmRkYzEyMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMTI1NDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRiZmY4ZjA3ZDAxZTdmMmMzOGI2MzUzZjdmZTJhNzZlYWJiODE4ODE3MWE2MjRiMjliZjk4MTdjNGQzYzA1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t8j518EbX3taRpIO7Bq276mMGSKiOteMfLT8OC3SfUc"> The hover effect looks wrong. Should find another solution

Do you mean because of the icon has white background on hover/open state?

2024-08-16 10:53 UTC, lha047 approved these changes
LGTM 👍

2024-08-16 10:55 UTC, merged