MTP-2541 Apply grid to align svg, linktext and after element on discl…
Mattilsynet/designsystem pull request #1143
Opened 2024-09-13 08:16 UTC by petterkoding

…osure link in menu

2024-09-20 05:47 UTC, lha047 requested changes
See comments

2024-09-20 05:47 UTC, lha047 commented on mt-kit/core/css/src/components/_disclosure.scss
> +    &[href] {
Is this specifically for the menu? If it is it should be with the rest of the menu stuff. Maybe there should be a separate menu style file

2024-09-20 05:47 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/content/MenuItems.svelte
> +          class="disclosure-header layout-flex layout-flex--center-vertical layout-full-width menu-level-1 align-items-center"
If you need a grid fot this to work the way you want. Then use the grid layout classes. Consider if you should remove the disclosure-header class here. As it is not really a disclosure header

2024-09-20 05:47 UTC, lha047 commented on mt-kit/core/css/src/components/_disclosure.scss
> +    &:not([href]) {
There should be no need to exclude stuff with a href.

2024-09-20 05:47 UTC, lha047 commented on mt-kit/core/css/src/components/_disclosure.scss
>    .disclosure-header {
This should work for all the disclosures in general. If you need something special for the menu, place it in the menu styling.

2024-09-25 09:44 UTC, lha047 commented on mt-kit/core/css/src/components/_disclosure.scss
> +    &.align-items-center {
Why not use grid on all the level 1 menu items?

2024-09-25 10:55 UTC, lha047 requested changes
Good :D See comments

2024-09-25 10:55 UTC, lha047 commented on mt-kit/core/css/src/components/_disclosure.scss
> +      line-height: $text-with-icon-line-height;
![Screenshot 2024-09-25 at 12 00 21](https://github.com/user-attachments/assets/c9f4e104-7fb1-4de9-9e1a-3d3413f2a9c8)
Look at the html implementation. This does not align all the stuff in the header. If you have chapter it looks like this.

2024-09-25 11:31 UTC, petterkoding commented on mt-kit/core/css/src/components/_dropdown.scss
> +    > a {
moving it to .menu-level-1

2024-09-25 11:32 UTC, petterkoding commented on mt-kit/core/css/src/components/_disclosure.scss
> +      line-height: $text-with-icon-line-height;
Designer has a plan to remove the icon, so it wont be a problem anymore. I will remove it

2024-09-26 09:12 UTC, lha047 approved these changes
good job 👍

2024-09-26 09:56 UTC, merged