MTP-2548 apply external icon on Highlighted content and -links
Mattilsynet/designsystem pull request #1151
Opened 2024-09-16 11:22 UTC by petterkoding

2024-09-17 11:42 UTC, lha047 requested changes
See comments

2024-09-17 11:42 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
>        flex-shrink: 0;
Did you check if you needed this? Looks to me like its not needed

2024-09-17 11:42 UTC, lha047 commented on mt-kit/core/css/src/global/_links.scss
> +      &::after {
Did you check if you needed this? Looks to me like its not needed

2024-09-17 13:22 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
>        flex-shrink: 0;
it is needed for mobile

![image](https://github.com/user-attachments/assets/0515316b-a5b1-455e-bde9-57080fdf9535)

2024-09-17 13:33 UTC, petterkoding commented on mt-kit/core/css/src/global/_links.scss
> +      &::after {
actually theres a  <p> wrapping the <a> in CardArticle.svelte. I can just remove the <p> Then there wont be a second icon.

2024-09-18 11:35 UTC, lha047 requested changes

2024-09-19 07:16 UTC, closed without merging