MT-650: hightlighted content
Mattilsynet/designsystem pull request #148
Opened 2021-12-17 11:00 UTC by lha047

Add component and styling for highlighted content

MT-650

2021-12-21 11:27 UTC, itemodahl requested changes
Good job! A couple of feedbacks you can take a look at.

2021-12-21 11:27 UTC, itemodahl commented on src/svelte/HighlightedContentLink.svelte
> +</a>
I don't think `div` is a valid content in an anchor element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a . Should we use `button` instead?

2021-12-21 11:27 UTC, itemodahl commented on src/ts/utils.ts
> +}
Should the check if isoDate exists happen outside this function. And instead make isoDate mandatory argument?

2021-12-22 08:44 UTC, lha047 commented on src/svelte/HighlightedContentLink.svelte
> +</a>
Looks to me like you should not use interactive elements either inside link.

2022-01-04 07:49 UTC, merged