Created a SummaryDetail component (WIP)
Mattilsynet/designsystem pull request #242
Opened 2022-02-10 11:37 UTC by miloszhygen

2022-02-10 14:56 UTC, lha047 requested changes
Nice work :D

Just have some small comments

2022-02-10 14:56 UTC, lha047 commented on src/svelte/SummaryDetail.svelte
> +<div class="wrapper">
Probably dont need this wrapper. Doesnt do anything

2022-02-10 14:56 UTC, lha047 commented on stories/components/SummaryDetail.stories.svelte
>      <h1>Detail summary</h1>
```suggestion
    <h1>Oppsummering og detaljer</h1>
```
Forslag til norsk navn?

2022-02-10 14:56 UTC, lha047 commented on stories/components/SummaryDetail.stories.svelte
> +      <p>
Would be nice if the details also could be edited in Storybook action control

2022-02-10 14:56 UTC, lha047 commented on stories/components/SummaryDetail.stories.svelte
>    title="Components/Summary Detail"
Klarer vi å finne et norsk navn på denne? :P Oppsummering og detaljer?

2022-02-10 14:56 UTC, lha047 commented on src/svelte/SummaryDetail.svelte
> +</div>
Add an empty line

2022-02-10 22:21 UTC, miloszhygen commented on stories/components/SummaryDetail.stories.svelte
>    title="Components/Summary Detail"
If I change `title="Components/Summary Detail"` to `title="Components/Oppsummering og Detaljer"` I get an error "Are you sure a story with that id exists?" Maybe I have to change the component file name too?

2022-02-10 22:53 UTC, miloszhygen commented on src/scss/components/_legal-collection.scss
> +  }
@lha047 I added margin top and bottom to this class

2022-02-11 06:50 UTC, lha047 approved these changes
Nice work :D

Would like for it to have tests as well, but closing and merging for now :D

2022-02-11 06:51 UTC, merged