Removed padding, margin and border LEFT for summary-detail style
Mattilsynet/designsystem pull request #260
Opened 2022-02-21 10:05 UTC by miloszhygen

2022-02-23 09:08 UTC, lha047 requested changes
Just wonder if this should be removed from all summery details

2022-02-23 09:08 UTC, lha047 commented on src/scss/components/_summary-details.scss
> -      margin-left: var(--detail-margin);
Should this be for all summary details?

2022-02-28 12:49 UTC, lha047 requested changes

2022-03-01 12:36 UTC, lha047 requested changes
<img width="528" alt="Screenshot 2022-03-01 at 13 34 24" src="https://user-images.githubusercontent.com/1166832/156170011-53fe29de-3833-4f6c-8864-e441c5ca0f5c.png">

Den brune linja under oppsummeringen skal ikke være der på den uten linjer, padding og marg :P

2022-03-01 12:39 UTC, miloszhygen commented
fixed @lha047 That was the conflict when rebasing.

2022-03-01 12:45 UTC, lha047 approved these changes
All good :D Good job

2022-03-01 12:46 UTC, merged