💄 MT-891  Moved style out of the article-spacing mixin
Mattilsynet/designsystem pull request #265
Opened 2022-02-23 14:10 UTC by miloszhygen

the summary details needs less space on top and bottom.

2022-02-25 07:11 UTC, lha047 requested changes
Code looks good :D 

Could you make a story for legal guidance collection?

2022-02-25 07:11 UTC, lha047 commented on src/scss/components/_legal-collection.scss
>  .legal-collection {
Can you add a `LegalGuidanceCollection.stories.svelte` to display how the legal guidance collection should look like?

2022-02-25 07:59 UTC, miloszhygen commented on src/scss/components/_legal-collection.scss
>  .legal-collection {
I'll fix :)

2022-02-28 13:57 UTC, lha047 approved these changes
Looks good :D

2022-02-28 13:57 UTC, merged