:zap: Mt 882 add h4 tag title card article
Mattilsynet/designsystem pull request #291
Opened 2022-03-08 11:03 UTC by miloszhygen

2022-03-10 07:50 UTC, lha047 requested changes
See my comment :)

2022-03-10 07:50 UTC, lha047 commented on src/svelte/CardArticle.svelte
> +    <h4 id={headingId} class="title">{@html title}</h4>
Did you have this throught desing review?
Looks like the styling is a bit different. Maybe use the same class `h3` as for the h2 tag?

2022-03-10 09:05 UTC, miloszhygen commented on src/svelte/CardArticle.svelte
> +    <h4 id={headingId} class="title">{@html title}</h4>
I'll test, and take it through design review :)

2022-03-10 12:15 UTC, miloszhygen commented
Added the class h4 to the h4 tag after the design review

2022-03-17 15:31 UTC, lha047 approved these changes
Good job :D

2022-03-17 15:31 UTC, merged