💄 MT 828: Decrease max length on text
Mattilsynet/designsystem pull request #337
Opened 2022-04-04 13:00 UTC by itemodahl

2022-04-05 05:44 UTC, lha047 requested changes
I guess you have something in the web project as well? 
The ´.children-full-width´ should be full width as described by the class name. Individual children elements can take up less space by individual targeting.

Have Malin look at the sizing before PR

2022-05-18 07:51 UTC, lha047 requested changes
Nice :D 
Have a look at the comments

2022-05-18 07:51 UTC, lha047 commented on src/scss/components/_top-tasks.scss
> +    max-width: 47.5rem;
This should not be neccesary. The `col-x-span-x` should do this work.

2022-05-18 07:51 UTC, lha047 commented on src/scss/components/_article.scss
> +      max-width: 47.5rem;
This should not be neccesary. The `grid-column: 3 / span 8;` should do this work.

2022-05-18 07:51 UTC, lha047 commented on stories/components/content/TopTasks.stories.svelte
> +      <div class="top-tasks-text col-1-span-6">{@html intro}</div>
Remember to do this update in the web-project as well :)

2022-05-18 07:51 UTC, lha047 commented on stories/components/content/LegalGuidanceCollection.stories.svelte
> +          class="legal-collection legal-collection__border-top col-3-span-6"
Remember to do this update in the web-project as well :)

2022-05-18 13:27 UTC, closed without merging

2022-05-18 13:28 UTC, itemodahl commented
This was added in https://github.com/Mattilsynet/designsystem/pull/402