✨  Mt 1215 dialogbox
Mattilsynet/designsystem pull request #450
Opened 2022-06-14 08:06 UTC by miloszhygen

2022-06-14 09:50 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +<div class={dialogBoxClosed ? 'dialog-box--closed' : 'dialog-box'} data-testid="dialog-box">
Challenge :P Try to limit the use of divs

2022-06-14 11:52 UTC, miloszhygen commented on src/svelte/DialogBox.test.ts
> +    const { getByTestId } = render(DialogBox, componentOptions)
The component does not contain any text to query :)

2022-06-14 11:53 UTC, miloszhygen commented on src/svelte/DialogBox.test.ts
> +    const componentOptions = {
Same as above ☝️

2022-06-14 12:11 UTC, miloszhygen commented on src/scss/components/_dialog-box-closable.scss
> +    background-color: green;
removed :)

2022-06-14 13:12 UTC, lha047 commented on src/svelte/DialogBox.test.ts
> +    const { getByTestId } = render(DialogBox, componentOptions)
If you put the aria-label which looks to be required. There should be a label to query ;)

2022-06-14 13:33 UTC, lha047 commented on src/scss/components/_dialog-box-closable.scss
> +  background-color: $color-mt-lighter-light-blue;
Its possible to use css variables on colors as well. See other places too

2022-06-17 11:19 UTC, lha047 requested changes
Found some more a11y things :)

2022-06-17 11:19 UTC, lha047 commented on src/scss/components/_dialog-box-closable.scss
> +
Need focus styling

2022-06-17 11:19 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +  role="dialog"
Missing `aria-label` or `aria-labelledby`. `role=dialog` should have a label. If you look in the storybook addon for a11y you see the a11y error. 

Maybe heading should be passed to the component? And then use `aria-labelledby`

2022-06-21 07:54 UTC, lha047 requested changes
Left some comments about a11y and focus style

2022-06-21 07:54 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +    <p id="title">{dialogBoxTitle}</p>
This should be a heading. I guess h2. But ask Malin.

2022-06-21 07:54 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +    <p id="title">{dialogBoxTitle}</p>
The id should be something unique. There is a chance `id="title"` occurs on a page. I suggest using something like:
```
<script context="module" lang="ts">
  let instanceCounter = 0
</script>
<script lang="ts">
  const dialogBoxHeadingId = `ui-dialog-box-${instanceCounter++}`
</script>
```
There is an example in `Select.svelte`

2022-06-21 07:54 UTC, lha047 commented on src/scss/components/_dialog-box-closable.scss
> +
Still need focus styling

2022-06-21 11:19 UTC, miloszhygen commented on src/scss/components/_dialog-box-closable.scss
> +
could I use `@include focus-outline();` ?

2022-06-24 10:33 UTC, lha047 requested changes
Nice job on the focus and styling

There is still some issues with screen reader I think. Also have some suggestions on readability

2022-06-24 10:33 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +  export let dialogBoxClosed: boolean = false
```suggestion
  export let isOpen: boolean = true
```
The closed = false got me abit confused. Felt its easier to read using the true value.
I prefer to prefix booleans with `is`. Dont think you need `dialogBox` its already in the component name.

2022-06-24 10:33 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +  export let dialogBoxTitle: string = ''
```suggestion
  export let title: string = ''
```

2022-06-24 10:33 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +  export let closeBtnLabel: string = 'Lukk'
```suggestion
  export let closeBtnAriaLabel: string = 'Lukk'
```
To make it explisit

2022-06-24 10:33 UTC, lha047 commented on stories/components/DialogBox.stories.svelte
> +    <DialogBox {dialogBoxClosed} {closeBtnLabel}>
It should have been a way to enforce title of the box. Voice over reads "Lukk dialogboks" as the title of the dialog.

2022-06-24 10:33 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +    <button
Could the button be after the title in the DOM order? It feels weird when Voice Over reads "Look dialogboks" before the title.

2022-06-24 12:28 UTC, miloszhygen commented on src/svelte/DialogBox.svelte
> +  export let dialogBoxClosed: boolean = false
Good point 👍

2022-06-24 12:29 UTC, miloszhygen commented on stories/components/DialogBox.stories.svelte
> +    <DialogBox {dialogBoxClosed} {closeBtnLabel}>
Hmm... yes, this is unfortunate, I'll see if its possible to fix the order of what is read first

2022-06-24 21:28 UTC, miloszhygen commented on stories/components/DialogBox.stories.svelte
> +    <DialogBox {dialogBoxClosed} {closeBtnLabel}>
I have changed the order of the elements :)

2022-06-27 12:31 UTC, lha047 approved these changes
Nice work 🎉 

Left some comments about rem vs px.

2022-06-27 12:31 UTC, lha047 commented on src/scss/components/_feedback-container.scss
>    --width-outside-content: 100px;
Can this be defined in rem?

2022-06-27 12:31 UTC, lha047 commented on src/scss/components/_feedback-container.scss
> +  --feedback-box-width: 260px;
Can this be defined in rem?

2022-06-27 12:31 UTC, lha047 commented on src/scss/components/_dialog-box-closable.scss
> +  --focus-box-shadow: 0 0 0 2px var(--color-mt-background),
Can this be defined in rem?

2022-06-27 12:51 UTC, merged