:zap: Mt 1215 dialogbox fix
Mattilsynet/designsystem pull request #471
Opened 2022-06-28 10:32 UTC by miloszhygen

2022-06-28 12:26 UTC, lha047 requested changes
See comments

2022-06-28 12:26 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +      <h2 id={dialogBoxHeadingId} class="h4 dialog-box--title" aria-label={title}>
Dont need aria-label on a heading?

2022-06-28 12:26 UTC, lha047 commented on src/svelte/DialogBox.svelte
> +  aria-label="dialog boks"
This cant be hard coded

2022-06-29 08:43 UTC, itemodahl approved these changes
Awesome job!

2022-06-29 08:45 UTC, merged