🐛 MT-1118: make voiceover annonce characters remaining
Mattilsynet/designsystem pull request #594
Opened 2022-10-21 08:12 UTC by itemodahl

* If more characters are entered, let user know how many characters exceeds the limit.

MT-1118

2022-10-24 10:57 UTC, lha047 requested changes
I cant build the web project with this version of DS.

`'countCharactersTooManyLabel' is not exported by node_modules/@mattilsynet/designsystem/src/svelte/form/TextArea.svelte, imported by node_modules/@mattilsynet/designsystem/src/svelte/form/TextInput.svelte
`

2022-10-31 10:56 UTC, amundlindstol commented
skal versjonen bumpes?

2022-11-01 09:34 UTC, itemodahl commented
@amundlindstol tenker du på når du tester?

2022-11-04 13:37 UTC, itemodahl commented on src/svelte/form/TextInput.svelte
> +  console.log('maxlength %s', JSON.stringify(maxlength, null, 2))
Removed

2022-11-04 13:50 UTC, lha047 approved these changes
Nice :D Bra jobba!

2022-11-10 11:50 UTC, merged