Add Chapter Menu component
Mattilsynet/designsystem pull request #66
Opened 2021-11-11 12:00 UTC by tajakobsen

Relates to: MT-490

2021-11-11 14:03 UTC, lha047 requested changes
Menu looks very nice :D
Just a few comments to use existing variables for colors etc.

2021-11-11 14:03 UTC, lha047 commented on src/scss/components/_chapter-menu.scss
> +    border-top: 1px solid var(--color-mt-background);
Thers a ```$border-width-small``` in ```_theme.scss``` for border width. Same below

2021-11-11 14:03 UTC, lha047 commented on src/scss/components/_chapter-menu.scss
> +    color: white;
```mt-white```

2021-11-11 14:12 UTC, tajakobsen commented on src/scss/components/_list.scss
> +    margin-top: 0;
I had it in the chapter menu first. But then I moved it here, because I thought that `.list-unstyled` should be as **neutral** as possible.

But you are right that it will affect other components, which is a problem. So I will move it back. But maybe we should consider making it a real feature.

2021-11-11 14:38 UTC, tajakobsen commented on stories/components/ChapterMenu.stories.svelte
> +  function chapterChange(e) {
Actually Storybook doesn't handle TypeScript in stories as of now. So I remove the `lang="ts"` on top.

2021-11-12 07:35 UTC, lha047 commented on stories/components/ChapterMenu.stories.svelte
> +  function chapterChange(e) {
ok

2021-11-12 07:37 UTC, lha047 approved these changes
Nice job :D

2021-11-12 07:37 UTC, merged