MT-452: Collaps breadcrumbs if it is longer than 3 elements
Mattilsynet/designsystem pull request #67
Opened 2021-11-11 14:54 UTC by itemodahl

MT-452

2021-11-12 10:15 UTC, tajakobsen approved these changes
Good job! A few things to look at though.

In general try to use *css custom properties* where you can.

Consider adding [json-ld](https://developers.google.com/search/docs/advanced/structured-data/breadcrumb) to this component, so that it is always applied together with the markup.
Maybe [this npm can be useful for types for json-ld](https://github.com/google/schema-dts)

2021-11-12 10:15 UTC, tajakobsen commented on src/scss/components/_buttons.scss
> +    min-width: 44px;
I don't think this is necessary. WCAG 2.5.5 is AAA, and I'm unsure if it applies to breadcrumbs, so I would probably not add this.

I would ensure that the elipsis button is large enough though.

2021-11-12 10:15 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
> +  $: breadcrumbData = breadcrumbs.items
`breadcrumbData` does not need to be responsive
```suggestion
  let breadcrumbData = breadcrumbs.items
```

2021-11-12 10:15 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
> +  let showAllBreadCrumbs = breadcrumbs.showAllAriaLabel ?? 'show all'
I would probably use norwegian words as fallback here, since this will most likely be used on norwegian pages.

2021-11-12 10:15 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
> +          collapsed: true
The values in this object is almost never used. Did you consider just using a constant string instead. It would make it easier to read.

```typescript
const BUTTON_ELIPSIS = Symbol();

breadcrumbData = [
    breadcrumbs.items[0],
    breadcrumbs.items[1],
    BUTTON_ELIPSIS,
    breadcrumbs.items[breadcrumbs.items.length -1]]
]
```

2021-11-12 10:15 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
>    interface Breadcrumbs {
If we want to be able to use this interface in the other application, move the interface to `.../ts/types.d.ts` so that it can be imported.

2021-11-12 10:15 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
> +  let spread = true
Did you consider using xstate for state management?

2021-11-12 10:15 UTC, tajakobsen requested changes
Just changing state "Request changes"

2021-11-12 11:50 UTC, itemodahl commented on src/svelte/Breadcrumbs.svelte
> +  let spread = true
I feel it is a bit overkill.

2021-11-15 13:30 UTC, itemodahl commented on src/scss/components/_buttons.scss
> +    min-height: 17px;
It is set to override the button default `min-height: 44px;`. The number comes from the sibling elements that are 17 px high. Changing it to auto.

2021-11-15 13:33 UTC, itemodahl commented on src/scss/components/_buttons.scss
> +    min-width: 44px;
Lisa said we should follow the required wcag standard. Setting it to "auto".

2021-11-16 09:48 UTC, tajakobsen requested changes
Looks good. I would still love to see a Symbol used as a placeholder for the elipsis in the array.

And maybe use of xstate.

2021-11-16 09:48 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
> +  const BUTTON_ELLIPSIS = {url: '', title: '...', collapsed: true}
I would still like to see a `Symbol()` used here.

2021-11-17 09:10 UTC, tajakobsen requested changes
Very good job! :+1: I just have a few small suggestions to look at.

2021-11-17 09:10 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
> +  let showAllBreadCrumbs = breadcrumbs.showAllAriaLabel ?? 'vis mer'
Maybe use a name that clarifies that this is a string meant as a label?

```suggestion
  let showAllBreadCrumbsLabel = breadcrumbs.showAllAriaLabel ?? 'vis mer'
```

2021-11-17 09:10 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
> +      breadcrumbsItems: []
If you to to turn of JavaScript (using Storybook) you will see that breadcrumbs doesn't render.

You should initialize this array with `breadcrumbs.items`, instead of an empty `array`.

2021-11-17 09:10 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
> +              cond: (() => breadcrumbs.items.length > 3)
If `context` was initialized with `breadcrumbs.items`, then you can probably use `context` as a parameter to the arrow function, and use it's value to do this check.

Also extract `3` into a named variable, so that someone reading this code can understand the meaning of `3`.

2021-11-17 09:10 UTC, tajakobsen commented on src/svelte/Breadcrumbs.svelte
> +        {:else if item === BUTTON_ELLIPSIS && !onServer}
Do we need `!onServer`? Because logically that can never be the case when `item === BUTTON_ELLIPSIS`

2021-11-17 10:20 UTC, tajakobsen requested changes
Good job. Maybe make the `3` a `const` instead of an `export let`.

2021-11-17 10:23 UTC, tajakobsen requested changes
Prettier has not been run on at least Breadcrumbs.svelte

2021-11-17 11:42 UTC, tajakobsen approved these changes
Great job! Closing and merging to main.

2021-11-17 11:42 UTC, merged