🌮 MTP-1164: Add search button inside search input field
Mattilsynet/designsystem pull request #715
Opened 2023-01-20 12:36 UTC by itemodahl

MTP-1164

2023-01-20 12:58 UTC, lha047 requested changes
Had a quick look :)
Left some comments. 
I think its better to make a separate search component. 
Have a look at using variables.

2023-01-20 12:58 UTC, lha047 commented on src/scss/components/_list.scss
> +    border-top: 1px solid var(--color-mt-beige-50);
Use variable for border width

2023-01-20 12:58 UTC, lha047 commented on src/scss/components/_list.scss
> +    padding: 28px;
Use spacer size

2023-01-20 12:58 UTC, lha047 commented on src/scss/components/_list.scss
> +      border-bottom: 1px solid var(--color-mt-beige-50);
Use variabel for border width

2023-01-20 12:58 UTC, lha047 commented on src/scss/components/_list.scss
> +      background-color: #fff;
Use variable for color

2023-01-20 12:58 UTC, lha047 commented on src/scss/components/_radio.scss
> +      border-bottom: 1px solid $color-secondary;
Use variable for border width

2023-01-20 12:58 UTC, lha047 commented on src/scss/components/_radio.scss
> +    right: 10px;
Use variables without px units

2023-01-20 12:58 UTC, lha047 commented on src/scss/components/_radio.scss
> +    bottom: 14px;
Use variables without px units

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/Tags.svelte
> +    border: 1px solid var(--color-mt-blue-medium);
Use variable

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/Tags.svelte
> +<style>
Move style to scss file

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/Tags.svelte
> +    border: 1px solid var(--color-mt-yellowgreen);
Use variable

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/Tags.svelte
> +    border: 1px solid var(--color-mt-beige);
Use variable

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/Tags.svelte
> +    padding: 4px 12px;
Use spacer var

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +  function mainCategory(mainIndex) {
Param typing. Retur type

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +  function subCategory(mainIndex, subCategoryKey) {
Typeing

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +                  <div class="form-control checkbox narrow">
Why do you need the extra div here? Can you use the li-tag

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +          <div class="form-control checkbox narrow">
Why do you need extra div here? Can you user the li-tag

2023-01-20 12:58 UTC, lha047 commented on src/svelte/components/form/TextInput.svelte
> +  export let searchButtonText: string | undefined
I suggest you create a separate search component. 
This one already have a lot doning on. The search is a separate thing `<input type="search"`

2023-01-20 12:58 UTC, lha047 commented on stories/components/form/CheckboxWithSubSets.stories.svelte
> +<script lang="ts">
I cant see this story

2023-01-23 12:48 UTC, lha047 requested changes
Still some work left here. 
Have a chat with UX about stats styling etc. 
Clean up the stories. The storybook should be useable for others now

2023-01-23 12:48 UTC, lha047 commented on stories/components/form/CheckboxWithSubSets.stories.svelte
> +    title: {control: 'text'},
Dont need this if its not shown

2023-01-23 12:48 UTC, lha047 commented on src/scss/_theme.scss
> +$spacer-xxxx-small: 0.25rem !default;// 4px
We should only have the spacers that are defined in Figma.
If you need other spacing start another group of variables

2023-01-23 12:48 UTC, lha047 commented on src/scss/_theme.scss
> +$spacer-x-small: 0.75rem !default; // 12px
We cant have two variables with the same name

2023-01-23 12:48 UTC, lha047 commented on src/scss/components/_tags.scss
> +  .medium {
There is minimal difference between this (medium) and the other kind. 
I think we should select one. Check with design

2023-01-23 12:48 UTC, lha047 commented on stories/components/List.stories.svelte
> +    showChapterNumber: true,
Dont need if you dont use

2023-01-23 12:48 UTC, lha047 commented on stories/components/List.stories.svelte
> +    disabled: false,
Dont need if you dont use

2023-01-23 12:48 UTC, lha047 commented on stories/components/List.stories.svelte
> +    showChapterNumber: {control: 'boolean'},
Dont need if you dont use

2023-01-23 12:48 UTC, lha047 commented on stories/components/List.stories.svelte
> +    disabled: {control: 'boolean'},
Dont need if you dont use

2023-01-23 12:48 UTC, lha047 commented on stories/components/List.stories.svelte
> +    disableCss: {control: 'boolean'}
Dont need if you dont use

2023-01-23 12:48 UTC, lha047 commented on stories/components/List.stories.svelte
> +  <List listContent={args.content} title={args.title} />
Cant see any list. The `<List>` has a slot not listContent

2023-01-23 12:48 UTC, lha047 commented on src/scss/components/_list.scss
> +    border-top: 0.0625rem solid var(--color-mt-beige-50);
Use variable

2023-01-23 12:48 UTC, lha047 commented on src/svelte/components/form/CheckboxWithSubSets.test.ts
> +  })
Should include click on the checkbox to display the next level and check that that displays ok

2023-01-23 12:48 UTC, lha047 commented on src/svelte/components/form/TextInputSearch.svelte
> +  export let value
```suggestion
  export let value: string
```

2023-01-24 08:57 UTC, amundlindstol commented on src/svelte/components/form/Search.svelte
> +    <Label class={labelClass} for={name}>
this is marked as not required in enonic. check for undefined here or require in enonic

2023-01-24 11:22 UTC, amundlindstol requested changes

2023-01-24 11:22 UTC, amundlindstol commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +    <p id="">{helpText}</p>
id=""

2023-01-24 11:22 UTC, amundlindstol commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +              style="padding-left: 20px"
change with class="p-l-s" or add p-l-xs in _utils.scss

2023-01-27 13:48 UTC, amundlindstol approved these changes
LGreatTM :D

2023-01-27 13:48 UTC, amundlindstol commented on src/scss/_theme.scss
> +$spacer-xxxx-small: 0.25rem !default;// 4px
```suggestion
```

2023-02-03 08:15 UTC, lha047 requested changes
Good job :D 
Left some more comments :)

2023-02-03 08:15 UTC, lha047 commented on stories/components/form/Search.stories.svelte
> +        <TextInputSearch name="inputfield_2" {label} {searchButtonText} labelClass="small" />
```suggestion
        <TextInputSearch name="inputfield_2" {label} {searchButtonText} />
```

2023-02-03 08:15 UTC, lha047 commented on stories/components/form/Search.stories.svelte
> +          labelClass="small" />
```suggestion
          />
```

2023-02-03 12:36 UTC, lha047 requested changes
Nice :D

Tags need to be related to link for screenreaders if used. Remove from story if tags are not to be used

2023-02-08 07:39 UTC, lha047 requested changes
Nice :D 

Left some comments. The tags story can stay

2023-02-08 07:39 UTC, lha047 commented on stories/components/List.stories.svelte
> +<Story name="Normal" let:args let:disableCss let:disabled let:secondary let:colorScheme>
Remove vars that are not used

2023-02-08 07:39 UTC, lha047 commented on src/scss/components/_tags.scss
> -  .lightblue {
The tag colors can stay :)

2023-02-08 07:39 UTC, lha047 commented on stories/components/Tags.stories.svelte
> -    <h2>Tags med forskjellige farger</h2>
The color tags can stay. We have them in the DS

2023-02-08 07:39 UTC, lha047 commented on src/scss/components/_tags.scss
> +    height: fit-content;
You should not need this

2023-02-08 07:39 UTC, lha047 commented on stories/components/Tags.stories.svelte
> +
The color tags can stay. We should have them in the DS

2023-02-08 07:39 UTC, lha047 commented on src/scss/components/_list.scss
> +    display: flex;
Remove the flex-box styling. We dont need it

2023-02-10 11:19 UTC, lha047 commented on src/scss/components/_list.scss
>      justify-content: space-between;
Remove `justify-content` and `align-content`

2023-02-10 13:03 UTC, lha047 approved these changes
Nice :D

2023-02-10 13:07 UTC, merged