Responsive stepper
Mattilsynet/designsystem pull request #72
Opened 2021-11-15 15:09 UTC by lha047

Relates to MT-444

2021-11-16 08:59 UTC, itemodahl requested changes
Very good! 

Only one change request: that we should be able to add localized phrases into the steps. With a Norwegian fallback.

2021-11-16 08:59 UTC, itemodahl commented on stories/FormSteps.stories.svelte
> +    currentText="Gjeldene side"
These two should be localized, with a fallback in Norwegian.

2021-11-17 12:49 UTC, lha047 commented on stories/FormSteps.stories.svelte
> +    currentText="Gjeldene side"
Dont think its necessary in the story. (We dont have the localize function in this project)

2021-11-19 10:23 UTC, tajakobsen requested changes
Good job. But I have a few things to take a look at.

2021-11-19 10:23 UTC, tajakobsen commented on src/svelte/FormSteps.svelte
> +  export let completed: number = 0;
Intellij suggests removing `:number` since it's easy to infer it here.

2021-11-19 10:23 UTC, tajakobsen commented on src/svelte/FormSteps.svelte
> +  role="progressbar"
I actually don't think you can add `role="progressbar"` to `<ol>`. You change the semantics of the element, and then the child `<li>` doesn't make sense.

2021-11-19 10:23 UTC, tajakobsen commented on src/svelte/FormSteps.svelte
> +  export let ariaValueText = `Steg ${completed + 1} av ${labels.length}`;
It reads out which step is completed, when you would think it reads out which step you are currently on.
```suggestion
  export let ariaValueText = `Steg ${completed + 2} av ${labels.length}`;
```

2021-11-19 10:23 UTC, tajakobsen commented on src/svelte/FormSteps.svelte
> +  export let ariaValueText = `Steg ${completed + 1} av ${labels.length}`;
Does this need to have `export`?

2021-11-19 10:23 UTC, tajakobsen commented on src/svelte/FormSteps.svelte
> +      {/if}
Are you getting any of the `inclusively-hidden` texts in your screen reader? I'm only experiencing the `role="progressbar"`.

If they are not used, maybe we shouldn't have them?

2021-11-19 10:23 UTC, tajakobsen commented on src/scss/components/_form-steps.scss
> +    font-size: 0;
What is up here? `font-size: 0;`?

2021-11-19 12:33 UTC, lha047 commented on src/scss/components/_form-steps.scss
> +    font-size: 0;
Its to make the text disappear on small screen safari. 
The alternative is to put a `<span class="responsive-hide">{label}</span>`. This is needed because of the `:before` and `:after`

2021-11-23 08:04 UTC, tajakobsen requested changes
Good job, we are getting close. You dodn't address the comment I had before about `ariaValueText`.

And I think we need something to make that `font-size: 0` more clear to readers.

2021-11-23 08:04 UTC, tajakobsen commented on src/scss/components/_form-steps.scss
> +    font-size: 0;
I have never seen this done before.

I see two options here.
 1. Change the code to add a class like you write above
 2. Add a comment here to clarify what is happening. Because this might confuse other future readers that haven't seen this before either.

2021-11-23 08:29 UTC, lha047 commented on src/svelte/FormSteps.svelte
> +  export let ariaValueText = `Steg ${completed + 1} av ${labels.length}`;
I think it should be so it can be translated

2021-11-23 09:20 UTC, lha047 commented
I think we should keep the `export` on `ariaValueText ` for translation

2021-11-23 13:33 UTC, tajakobsen approved these changes
Looks good. Closing and merging to main

2021-11-23 13:33 UTC, merged