MT-447: Add expadable box
Mattilsynet/designsystem pull request #75
Opened 2021-11-17 10:53 UTC by itemodahl

2021-11-18 08:43 UTC, lha047 requested changes
The component looks good :D
I have some suggestions for improvements. Maybe we should discuss some of them?

2021-11-18 08:43 UTC, lha047 commented on src/scss/components/_expandable-box.scss
> +    color: white;
Use the `mt-white` color

2021-11-18 08:45 UTC, lha047 commented on src/scss/components/_expandable-box.scss
> +  min-width: 331px;
Can we use the `rem` unit?
Check all the places where `px` is used. We want to use some scaleable unit such as `rem`. This scales on responsive, zooming etc

2021-11-18 09:52 UTC, tajakobsen requested changes
Have a look at the changes I've pointed out. I also recommended changing the name of the whole component.

And please run prettier automatically! It has not been run on this code.

2021-11-18 09:52 UTC, tajakobsen commented on src/svelte/ExpandableBox.svelte
> +          class:chevron-up={isOpen}
It should also have `aria-haspopup="true"`

2021-11-18 09:52 UTC, tajakobsen commented on src/svelte/ExpandableBox.svelte
> +          type="button" on:click={() => send('TOGGLE')}>
We do not need `type="button"` on a `<button>`

2021-11-18 09:52 UTC, tajakobsen commented on src/svelte/ExpandableBox.svelte
> +      <slot />
I like the `<slot>`, It's more flexible. And I'm pretty sure we'll need this later.

2021-11-18 09:52 UTC, tajakobsen commented on stories/ExpandableBox.stories.svelte
> +            <a href={item.url} class="forward-arrow-small" aria-label={item.ariaLabel}>
You should not be using an `aria-label` here. The text content of `<a>` is clear and good.

2021-11-18 09:52 UTC, tajakobsen commented on stories/ExpandableBox.stories.svelte
> +        ariaLabel: 'Les innhaldet på nynorsk'
Remove `ariaLabel`, we don't need it with good text content.

2021-11-18 09:52 UTC, tajakobsen commented on src/svelte/ExpandableBox.svelte
> +          class:chevron-down={!isOpen}
We don't need the classes here. Use `[aria-expanded]` in your css (same as Disclosure).

2021-11-18 09:52 UTC, tajakobsen commented on src/svelte/ExpandableBox.svelte
> +<script lang="ts">
I don't like the name "ExpandableBox". I think "Dropdown button" is probably a more wellknown name for this widget.

2021-11-18 09:52 UTC, tajakobsen commented on src/scss/components/_expandable-box.scss
> +  .alt-language {
If the list of languages is a separate thing then "expandable box", try separating out that list as a real separate component with it's own naming not closely related to languages.

2021-11-18 09:52 UTC, tajakobsen commented on src/svelte/ExpandableBox.svelte
> +      <slot />
But wrap the slot in a `<div>` and use a `transition` (same as Disclosure) to get an opening animation.

2021-11-18 09:52 UTC, tajakobsen commented on src/scss/components/_buttons.scss
> +  }
You can use the svg directly in content, instead of using a more hackish solution with backgrounds.

```suggestion
    content: url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMTIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTE4LjIxNCAwIDEwIDguMzY0IDEuNzg2IDAgMCAxLjgxOCAxMCAxMiAyMCAxLjgxOCAxOC4yMTQgMFoiIGZpbGw9IiMzRjNFM0UiLz48L3N2Zz4=");
  }
```

2021-11-18 09:52 UTC, tajakobsen commented on src/scss/components/_buttons.scss
> +    background-image: url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMTIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTEuNzg2IDEyIDEwIDMuNjM2IDE4LjIxNC
Prefer to rotate the chevron, instead of replacing the svg. Then we can animate it. Have a look at how it's done in Disclosure.

2021-11-18 09:52 UTC, tajakobsen commented on stories/ExpandableBox.stories.svelte
> +      <ol class="alt-language" >
This `<ol>` should have `aria-labelledby="id-of-expandable-box-button"`. The id for an expandable-box-button should be unique on the page, and be exposed as `<ExpandableBox let:buttonId>`.

2021-11-18 09:52 UTC, tajakobsen commented on src/svelte/ExpandableBox.svelte
> +      isOpen: false
This context is not being used, and can be removed.

2021-11-19 09:37 UTC, tajakobsen requested changes
Good job. But I still have a few more things that should be looked at.

2021-11-19 09:37 UTC, tajakobsen commented on src/scss/components/_buttons.scss
> +  border: 0.125rem solid transparent;
We should be using constants from the designsystem for these values.

2021-11-19 09:37 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +      content: url("data:image/svg+xml,%3Csvg width='20' height='12' fill='white' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M18.214 0 10 8.364 1.786 0 0 1.818 10 12 20 1.818 18.214 0Z' /%3E%3C/
Is this `content` needed now, if we just rotate the other content?

2021-11-19 09:37 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +    &.chevron::after {
Do we need a separate `.chevron` class? I think instead we should just relate this `::after`  to `[aria-expanded]` keeping it simple.
```suggestion
    &[aria-expanded]::after {
```

2021-11-19 09:37 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +    &[aria-expanded='true'].chevron::after  {
Can remove `.chevron` here too.

2021-11-19 09:37 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +      padding: 0.375rem;
Use css custom properties for padding-size.

2021-11-19 09:37 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +        box-shadow: 0 0 0 0.25rem white;
Is this from Figma? I thought the contrast was a bit much. Maybe a background change on `a` would be nicer?

2021-11-19 09:37 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +    a {
I would prefer these to be `width: 100%`

2021-11-19 09:37 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +      border-radius: 0.4375rem;
Is this from Figma? I'm unsure about the border-radius...

2021-11-19 09:37 UTC, tajakobsen commented on src/svelte/Dropdown.svelte
> +  interface DropdownContext {}
Missing `isFirstRenderFinished` from `DropdownContext`.

2021-11-19 09:37 UTC, tajakobsen commented on src/svelte/Dropdown.svelte
> +  export let bodyId = '';
`bodyId` should be generated by incrementing a counter in `context="module"`. See [example from Disclosure](https://github.com/Mattilsynet/designsystem/blob/main/src/svelte/Disclosure.svelte#L27)

There should also be a `let buttonId` that uses the same counter when generated. This value should be exposed, so that the class calling this can use `aria-labelledby={buttonId}`

2021-11-19 09:37 UTC, tajakobsen commented on src/svelte/Dropdown.svelte
> +  export let bodyId = '';
Don't need to export `bodyId`.

2021-11-19 09:37 UTC, tajakobsen commented on src/svelte/Dropdown.svelte
> +        on: {TOGGLE: 'open'}
Missing actions to handle `isFirstRenderFinished`

2021-11-19 09:37 UTC, tajakobsen commented on stories/Dropdown.stories.svelte
> +<Story name="Normal" args={config} let:args>
We should a story with multiple dropdowns on the same page.

2021-11-19 09:37 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +  text-align: right;
I'm kind of missing some configuration in the part where the alignment of the button should be...

For most usages of a dropdown, this would probably on the left.

There should be a story for both left-aligned and right-aligned button.

2021-11-19 09:37 UTC, tajakobsen commented on stories/Dropdown.stories.svelte
> +<Meta
Enable xstate in `<meta>`
```html
  parameters={{xstate: true, inspectUrl: 'https://stately.ai/viz?inspect'}}
```

2021-11-19 09:37 UTC, tajakobsen commented on stories/Dropdown.stories.svelte
> +        homeLabel: 'hjem',
I don't see `homeLabel` being used anywhere.

2021-11-19 09:44 UTC, tajakobsen requested changes

2021-11-19 09:44 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +  button {
`focus` indicator on the button doesn't show when background is blue.

2021-11-19 10:13 UTC, itemodahl commented on src/scss/components/_dropdown.scss
> +      content: url("data:image/svg+xml,%3Csvg width='20' height='12' fill='white' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M18.214 0 10 8.364 1.786 0 0 1.818 10 12 20 1.818 18.214 0Z' /%3E%3C/
Since the chevron change colour, I need to set a different content here.

2021-11-19 10:34 UTC, itemodahl commented on src/scss/components/_dropdown.scss
> +  text-align: right;
Wouldn't this be premature optimization?

2021-11-19 10:35 UTC, itemodahl commented on stories/Dropdown.stories.svelte
> +        homeLabel: 'hjem',
I must have mixed up the files with the breadcrumbs files

2021-11-19 12:03 UTC, itemodahl commented on stories/Dropdown.stories.svelte
> +<Story name="Normal" args={config} let:args>
Wouldn't this be premature optimization?

2021-11-19 13:39 UTC, tajakobsen commented on src/scss/components/_dropdown.scss
> +  text-align: right;
Yes maybe. We can save this for when we need it.

2021-11-19 13:40 UTC, tajakobsen commented on stories/Dropdown.stories.svelte
> +<Story name="Normal" args={config} let:args>
I think that all components we build should support multiple instances on a page. And that ensuring unique ids used is part of that.

2021-11-23 13:27 UTC, tajakobsen requested changes
There are still some issues around position absolute that needs to be handled. We can look at it togheter if you want.

2021-11-23 13:27 UTC, tajakobsen commented on stories/Dropdown.stories.svelte
> +      <Dropdown title={args.buttonLabel} bodyId={args.bodyId} loadJs={!args.disableJs}>
This is still setting `bodyId`, and not exposing `titleId`

2021-11-23 13:27 UTC, tajakobsen commented on stories/Dropdown.stories.svelte
> +    <section class={`preview-wrapper preview-wrapper-${i}`} style={`z-index:${configs.length - i}`}>
The `z-index` is just obfuscating a bug that should be handled. I think the `<nav>` element probably should have the `position: relative`.

The `<slot>` should be positioned based under the button.

2021-11-23 13:27 UTC, tajakobsen commented on stories/Dropdown.stories.svelte
> +    <section class={`preview-wrapper preview-wrapper-${i}`} style={`z-index:${configs.length - i}`}>
Why is `.preview-wrapper-${i}` being set?

2021-11-25 08:01 UTC, tajakobsen requested changes
Good job forward. I've re-reviewed this with a few more comments.

2021-11-25 08:01 UTC, tajakobsen commented on src/svelte/Dropdown.svelte
> +    <div class="dropdown-content" id={bodyId} in:slide={{duration: 100, easing: sineIn}}>
Just bump `duration` to `300` again. I don't see the yanking anymore. It might have to do with absolute position.

2021-11-25 08:01 UTC, tajakobsen commented on stories/Dropdown.stories.svelte
> +        <ol class="alt-language" aria-labelledby={args.bodyId}>
```suggestion
        <ol class="alt-language" aria-labelledby={titleId}>
```

2021-11-25 08:07 UTC, lha047 requested changes
I have some comments :)

2021-11-25 08:07 UTC, lha047 commented on src/scss/components/_dropdown.scss
> +    z-index: 1000;
Maybe we should have a variable in `_theme.scss` for the z-indexes used?

2021-11-25 08:07 UTC, lha047 commented on src/scss/global/_links.scss
>        height: 21px;
There are still some `px` used. Use rems :). Maybe use variables to describe it if it does not fit in the "spacing"-variables

2021-11-25 12:26 UTC, itemodahl commented on src/scss/components/_dropdown.scss
> +    font-weight: var(--font-weight-light);
yes

2021-11-26 09:12 UTC, tajakobsen approved these changes
Looks good, closing and merging to main.

2021-11-26 09:12 UTC, merged