MTP-698_too_many_characters_feedback
Mattilsynet/designsystem pull request #766
Opened 2023-02-28 14:19 UTC by amundlindstol

2023-02-28 15:10 UTC, lha047 requested changes

2023-02-28 15:10 UTC, lha047 commented on src/svelte/components/form/TextInput.svelte
> +      on:input={e => {
<img width="384" alt="Screenshot 2023-02-28 at 16 07 01" src="https://user-images.githubusercontent.com/1166832/221894199-d6dc4dfe-d6dd-4869-b5f6-1576fe3ad004.png">

Something doesnt look right here :P Ask design how it should be

2023-03-02 12:06 UTC, lha047 commented on src/svelte/components/form/TextInput.svelte
> +<!--suppress XmlDuplicatedId -->
What is this? 🤔

2023-03-02 12:07 UTC, lha047 commented on src/svelte/components/form/TextArea.svelte
> +<!--suppress CheckEmptyScriptTag -->
What is this? 🤔

2023-03-07 12:34 UTC, amundlindstol commented on src/svelte/components/form/TextArea.svelte
> +<!--suppress CheckEmptyScriptTag -->
Intellij inspection complained on empty tag </> vs open tag <></>
But apparently Netscape 4 is the only browser not supporting it.
so i disabled HTML | Empty tag inspection in Settings | Editor | Inspections

2023-03-10 07:53 UTC, lha047 requested changes
Left some comments. Sorry didnt see this the first time arround

2023-03-10 07:53 UTC, lha047 commented on src/ts/count-characters.ts
> +  countCharsParams: Record<string, any>,
Maybe create at proper type for this. Dont like the any part of the record :P

2023-03-10 07:53 UTC, lha047 commented on src/scss/global/_typography.scss
> +.text-error {
Dont need this. There is a `color-error` class that does the exact same thing

2023-03-10 07:53 UTC, lha047 commented on src/ts/count-characters.ts
> +      counterElVisible.classList.add('text-error')
Use the `color-error` class to get the red text

2023-03-10 07:53 UTC, lha047 commented on src/svelte/components/form/TextInput.svelte
> +    on:input={e => {
Add a test for this new feature

2023-03-10 07:53 UTC, lha047 commented on src/svelte/components/form/TextArea.svelte
> +  on:input={e => {
Add a test for this new feature

2023-03-10 13:58 UTC, amundlindstol commented
I personally think the code duplication is ok

2023-03-14 07:33 UTC, lha047 approved these changes
Nice good job :D

2023-03-14 07:42 UTC, merged