Add react components to designsystem
Mattilsynet/designsystem pull request #768
Opened 2023-03-07 11:56 UTC by alexanderheirethenge

La til en ny pakke for react komponenter og storybook som viser komponentene

2023-03-07 13:23 UTC, lha047 requested changes
Cool :D
Didn't have the chance to look at this too closely. But left some comments about accessibility for now. Will look at it more later today.

2023-03-07 13:23 UTC, lha047 commented on mt-kit/core/react/src/form/InputLabel.tsx
> +  <label className={classNames('form-label', className)} {...rest}>{children}{textOptional &&
The label should be linked to the input with `for="<id>"` for accessibility (a11y)

2023-03-07 13:23 UTC, lha047 commented on mt-kit/core/react/src/form/InputHelpText.tsx
> +  <div className="hint">{text}</div> : null
The help text should be linked to the input for a11y. See how its done in the Svelte component

2023-03-07 13:23 UTC, lha047 commented on mt-kit/core/react/src/form/InputErrorMessage.tsx
> +  errorMessage ? <span className="form-error">{errorMessage}</span> : null
The error should be linked to the input for a11y. See how its done in the Svelte component

2023-03-07 13:23 UTC, lha047 commented on mt-kit/core/react/src/form/text-input/TextInput.tsx
> +    <InputLabel textOptional={textOptional}>{label}</InputLabel>
This should contain linking between input, label, helpText and error for a11y. See Svelte component

2023-03-07 20:11 UTC, lha047 commented on mt-kit/core/react/src/icon-button/IconButton.tsx
> +  <button className={classNames('icon-button', className)} {...rest}>{children}</button>
If you are passing only an icon as `children` this needs to have some sort of visually hidden text for a11y

2023-03-07 20:16 UTC, lha047 commented on mt-kit/core/react/src/button/Button.stories.tsx
> +export const Loading: Story = {
If the button only has an icon there should be a visually hidden text for screen readers.

2023-03-08 05:51 UTC, lha047 commented on src/scss/components/_buttons.scss
> +  padding: 0.5em;
I know this isnt done with the other button classes. But suggest creating a variable for the button padding so that we later can have design tokens for them.

2023-03-08 05:52 UTC, lha047 commented on src/scss/components/_buttons.scss
> +  border-radius: 50%;
Border radius should be a variable so we can use design tokens later

2023-03-08 05:56 UTC, lha047 commented on mt-kit/core/react/src/form/Input.tsx
> +const Input: React.FC<InputHTMLAttributes<HTMLInputElement>> = ({className, ...rest}): JSX.Element =>
Would like to discuss if we should have explicit interfaces for all components. Didnt look into it much, but I guess its possible to generate docs from the interfaces

2023-03-08 06:00 UTC, lha047 commented on mt-kit/core/react/package.json
> +    "storybook": "storybook dev -p 6006",
Would it be ok to start React storybook at a different port in case someone needs to run all storybooks locally? Maybe the main (not created yet) should run on the default storybook port?

2023-03-08 08:58 UTC, TheBoosja requested changes
Left some of my own comments too :slightly_smiling_face:

2023-03-08 08:58 UTC, TheBoosja commented on mt-kit/core/react/package.json
> +    "react": "18.x",
A lot of the projects hasn't upgraded to react 18 yet. Don't know if you can support multiple versions of React at the same time considering storybook

2023-03-08 08:58 UTC, TheBoosja commented on mt-kit/core/react/package.json
> +    "@mattilsynet/designsystem": "^0.14.1",
Missing prettier?

2023-03-08 08:58 UTC, TheBoosja commented on mt-kit/core/react/src/form/Input.tsx
> +const Input: React.FC<InputHTMLAttributes<HTMLInputElement>> = ({className, ...rest}): JSX.Element =>
And discuss what props should be and not be :slightly_smiling_face:

2023-03-08 08:58 UTC, TheBoosja commented on mt-kit/core/react/src/form/text-input/TextInput.tsx
> +    <InputLabel textOptional={textOptional}>{label}</InputLabel>
And consider `InputLabel.TextOptional` component

2023-03-09 14:37 UTC, alexanderheirethenge commented on mt-kit/core/react/package.json
> +    "storybook": "storybook dev -p 6006",
I changed this to port 6007

2023-03-09 14:39 UTC, alexanderheirethenge commented on mt-kit/core/react/package.json
> +    "react": "18.x",
Added support for React 17

2023-03-09 14:39 UTC, alexanderheirethenge commented on mt-kit/core/react/package.json
> +    "@mattilsynet/designsystem": "^0.14.1",
Added prettier and eslint now

2023-03-10 08:07 UTC, TheBoosja reviewed
Saw that you're using npm, rather than yarn. Unsure about how that will affect development for us, since we use yarn. I don't know if you can link an npm project with a yarn project. 
When developing on `mt-ui` we use `yarn link` to link the projects, so we can see how the changes affects our projects directly.

2023-03-10 11:28 UTC, alexanderheirethenge commented on mt-kit/core/react/src/button/LoadingButton.tsx
> +    {loading === true && <span style={{position: 'absolute'}} className="spinner" />}
I have tested linking it to our project which uses pnpm with `pnpm link`, and that works. I guess it should work with `yarn link` as well.

2023-03-10 11:30 UTC, alexanderheirethenge commented on mt-kit/core/react/src/button/LoadingButton.tsx
> +    {loading === true && <span style={{position: 'absolute'}} className="spinner" />}
We can use the naming convention your suggesting there. So i will rename it to `isLoading`

2023-03-10 11:41 UTC, TheBoosja commented on mt-kit/core/react/src/button/LoadingButton.tsx
> +    {loading === true && <span style={{position: 'absolute'}} className="spinner" />}
Fantastic! :tada:

2023-03-16 20:17 UTC, lha047 reviewed
Good job with changes.
Left some comments. 
We can discuss about merging this and fix things in the next round? What do you think? @alexanderheirethenge @TheBoosja

2023-03-16 20:17 UTC, lha047 commented on mt-kit/core/react/src/button/IconButton.stories.tsx
> +type Story = StoryObj<typeof IconButton>
Looks like this has a very small press surface. Consider making it bigger?
Not in norwegian accessibility regulations at the moment. But https://www.w3.org/WAI/WCAG21/Understanding/target-size.html 2.5.5 for press surface sais that it should be at least 44px*44px.

2023-03-16 20:17 UTC, lha047 commented on src/scss/components/_buttons.scss
> +$icon-button-border-radius: 50%;
Maybe consider making this the same border radius as the other buttons?

2023-03-17 07:28 UTC, TheBoosja commented on mt-kit/core/react/.prettierrc.json
I disagree with the `bracketSpacing` :slightly_smiling_face: I like my spacing. Creates a much cleaner look. Otherwise I have no objections.
I see we use `tabWidth: 2`.

2023-03-17 07:30 UTC, TheBoosja commented on mt-kit/core/react/src/button/Button.tsx
> +  ...rest
I definitely is all for this.

2023-03-17 07:37 UTC, TheBoosja commented on mt-kit/core/react/src/form/text-input/TextInput.tsx
> +  textOptional?: string
The `textOptional` prop is optional to use in the component. Shouldn't it keep being that way? We don't necessarily want extra text after the label, or what? And how would we decide what length the text can be, if the input field theoretically can be any width?

2023-03-17 07:42 UTC, TheBoosja commented on mt-kit/core/react/src/form/Input.tsx
> +const Input: React.FC<InputProps> = ({className, ...rest}): JSX.Element => {
Explicit but as limited as possible. Not with `InputHTMLAttrubutes<...>`. Only with what we desire the component to accomplish

2023-03-17 07:46 UTC, TheBoosja commented
> Good job with changes. Left some comments. We can discuss about merging this and fix things in the next round? What do you think? @alexanderheirethenge @TheBoosja

Sure, as long as we don't get too far in the work (on other components) that we forego to fix up the components and make them optimal

2023-03-20 07:26 UTC, lha047 commented on mt-kit/core/react/src/form/text-input/TextInput.tsx
> +  textOptional?: string
I agree that the `textOptional` can be optional. It needs to work together with the `required` attribute on the input field.

2023-03-20 07:28 UTC, lha047 commented on mt-kit/core/react/src/form/text-input/TextInput.tsx
> +  textOptional?: string
On the Svelte implementation there is also a counter for the `maxLength`. I suggest either removing the `maxLength` prop and the use of it, or implement it fully.

2023-03-20 07:37 UTC, TheBoosja commented on mt-kit/core/react/src/form/text-input/TextInput.tsx
> +  textOptional?: string
Ah, `required` as the input prop. I thought you meant to make `textOptional` required :sweat_smile:

2023-03-20 09:35 UTC, alexanderheirethenge commented on mt-kit/core/react/.prettierrc.json
We can use the following? `{
  "arrowParens": "avoid",
  "singleQuote": true,
  "trailingComma": "none",
  "semi": false,
  "printWidth": 100,
  "tabWidth": 2
}`

2023-03-21 13:12 UTC, alexanderheirethenge commented on mt-kit/core/react/src/button/Button.tsx
> +  ...rest
Yes, but I vote for doing this in the next round. We also need to figure out what props to include.

2023-03-21 13:18 UTC, alexanderheirethenge commented on mt-kit/core/react/src/form/text-input/TextInput.tsx
> +  textOptional?: string
I removed the `maxLength` prop for now. We can maybe implement it later. The `textOptional` is now only visible when `required` is false.

2023-03-21 13:18 UTC, alexanderheirethenge commented on mt-kit/core/react/src/button/LoadingButton.tsx
> +    <div style={{visibility: isLoading === true ? 'hidden' : 'visible'}}>{children}</div>
Added

2023-03-21 13:19 UTC, alexanderheirethenge commented on mt-kit/core/react/src/form/Input.tsx
> +const Input: React.FC<InputProps> = ({className, ...rest}): JSX.Element => {
Same as with Button. I think we can do this in the next round?

2023-03-21 13:22 UTC, alexanderheirethenge commented on mt-kit/core/react/src/button/IconButton.stories.tsx
> +type Story = StoryObj<typeof IconButton>
I changed the styling to use 44px for the min-height and min-width

2023-03-21 13:22 UTC, alexanderheirethenge commented on src/scss/components/_buttons.scss
> +$icon-button-border-radius: 50%;
Done

2023-03-21 18:47 UTC, lha047 approved these changes
LGTM :D Good job

Left two minor change requests. Don't like the px unit for responsiveness :P

2023-03-21 18:47 UTC, lha047 commented on src/scss/components/_buttons.scss
> +$icon-button-min-height: 44px;
```suggestion
$icon-button-min-height: 2.75rem;
```

2023-03-21 18:47 UTC, lha047 commented on src/scss/components/_buttons.scss
> +$icon-button-min-width: 44px;
```suggestion
$icon-button-min-width: 2.75rem;
```

2023-03-22 07:44 UTC, TheBoosja commented on mt-kit/core/react/src/form/text-input/TextInput.tsx
> +  textOptional?: string
I think I've misunderstood what is meant by `textOptional`. I thought of it as "extra" or "info" text, to describe the purpose of the input field further. Then it doesn't make sense to have it be dependent on `required`.
But if it's text to describe that the input field is optional, then I would say that maybe the `textOptional` shouldn't be a prop at all, but rather a hard-coded text that is shown when `required` is `false`.
What do you think? @alexanderheirethenge @lha047

2023-03-27 07:48 UTC, merged