MTP-1351-vise-antall-treff
Mattilsynet/designsystem pull request #772
Opened 2023-03-13 09:37 UTC by amundlindstol

2023-03-13 11:08 UTC, lha047 requested changes
I think we need to have an extra look at this with regards to accessibility

2023-03-13 11:08 UTC, lha047 commented on src/svelte/components/form/Search.svelte
> +{#if label}
If we are not going have a visible label. We need to have another way to explain what this is for accessibility

2023-03-13 11:08 UTC, lha047 commented on src/svelte/components/form/Search.svelte
> +  export let ariaControls: string | undefined
Where is the thing that the button controls?

2023-03-13 11:12 UTC, amundlindstol commented on src/svelte/components/form/Search.svelte
> +  export let ariaControls: string | undefined
https://github.com/Mattilsynet/mattilsynet-web/pull/358/files#diff-bfa4d0f215637200d8d16f37f6040e0f0d048cfde50ee1a51d34bb83601283a1R35-R40

2023-03-13 11:17 UTC, amundlindstol commented on src/svelte/components/form/Search.svelte
> +{#if label}
VoiceOver says: "search text field, search".
I feel like it gives the same amount of information as the design
![image](https://user-images.githubusercontent.com/21691168/224686885-7f6760e5-fca8-4c93-86a5-27095d50ae50.png)

2023-03-16 14:13 UTC, lha047 requested changes
Look at aria controls

2023-03-16 14:13 UTC, lha047 commented on src/svelte/components/form/Search.svelte
> +      {ariaControls}
This will not produce the right attribute. It is currently `ariacontrols` and needs to be `aria-controls`

2023-03-17 07:47 UTC, lha047 approved these changes
Good job :D

2023-03-17 07:48 UTC, merged