MTP-1455 filter changes
Mattilsynet/designsystem pull request #777
Opened 2023-03-23 13:09 UTC by itemodahl

MTP-1455

2023-03-29 12:06 UTC, amundlindstol requested changes

2023-03-29 12:06 UTC, amundlindstol commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +  let checkboxDOMElements = []
is this used?

2023-03-29 12:35 UTC, lha047 commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +  interface CheckboxWithSubSectionsStates {
Move under imports?

2023-03-29 12:36 UTC, lha047 commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +  export const checkboxes = {
Move under other exports?

2023-03-29 12:44 UTC, amundlindstol commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +  export let tabIndex = 0
unused

2023-03-29 14:21 UTC, itemodahl commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +        subSectionValues = subSectionValues.filter(value => !child.key.includes(value))
Agree. The last is unnecessary. Simplified and added some comments

2023-03-29 14:29 UTC, itemodahl commented on src/svelte/components/form/CheckboxWithSubSets.svelte
> +  let checkboxDOMElements = []
Yes. Since we are updating the categories and subcategories on each search result, I had to move the elements refs outside of the state. To avoid a situation where the element was bound to a deleted ref before svelte updated it.

2023-03-30 06:56 UTC, lha047 requested changes
Sub categories need to be unchecked when parent level is not check

2023-03-30 14:15 UTC, lha047 approved these changes
Good job :D

2023-03-31 07:04 UTC, lha047 requested changes
Testet with web. 
When selecting dyr/produksjonsdyr then filer.
![Screenshot 2023-03-31 at 09 00 14](https://user-images.githubusercontent.com/1166832/229047342-f7086ebc-8e72-4346-8592-988113337926.png)
The other main categories dissapare
![Screenshot 2023-03-31 at 09 00 21](https://user-images.githubusercontent.com/1166832/229047357-309d191a-e52f-453d-b550-280d9b05bb7f.png)

Maybe consider adding the buttons in this component so we can test everything here?

2023-03-31 07:20 UTC, lha047 approved these changes

2023-03-31 10:32 UTC, amundlindstol approved these changes
noice :D

2023-03-31 10:34 UTC, merged