Use common css
Mattilsynet/designsystem pull request #813
Opened 2023-04-14 06:19 UTC by lha047

2023-04-14 07:48 UTC, TheBoosja requested changes

2023-04-14 07:48 UTC, TheBoosja commented on .storybook/preview.js
> +import '@mattilsynet/designsystem-css/dist/app.css'
Is it possible to remove `dist` from this. Ideally, I think it should be something like:
```suggestion
import '@mattilsynet/designsystem-css/app.css'
```

2023-04-14 07:48 UTC, TheBoosja commented on mt-kit/core/css/package.json
> +    "src/utilities/colors.js"
I think we should only expose what we must. If it is possible to just publish `app.css` and the files under `src`, so that practically it becomes:
```
import '@mattilsynet/designsystem-css/app.css'
import '@mattilsynet/designsystem-css/_theme.scss'
import '@mattilsynet/designsystem-css/_color-tokens.scss'
import '@mattilsynet/designsystem-css/utilities/_mixins.scss'
import '@mattilsynet/designsystem-css/utilities/colors.js'
```
We can talk further about the filestructure and folders, but I think the project specific filestructure should not be exposed in the published package. What do you think?

2023-04-14 10:50 UTC, lha047 commented on mt-kit/core/css/package.json
> +    "src/utilities/colors.js"
Yepp I agree :) Will try fix it :P

2023-05-22 07:45 UTC, TheBoosja approved these changes

2023-07-12 09:55 UTC, merged