MTP-546 Bytte ut knapper med lenker
Mattilsynet/designsystem pull request #833
Opened 2023-04-27 09:24 UTC by petterkoding

- Refactored link--transport class, new style modifiers: --primary, --secondary, -large.
- Updated CardArticle to use link--transport and removed unnecessary classes
- Removed unused styling classes on CardArticle.test.ts
- Updated Stories that used old styling to only use link--transport class

2023-04-27 10:54 UTC, petterkoding commented on src/svelte/components/CardArticle.svelte
> +        class:link--transport={linkTypeTransport}>
is the CardArticle and its' anchor tag used anywhere without the **forward-arrow-end** icon at the end (just styled as default anchor tag)??

If not, then the exported prop `linkTypeTransport` isn't needed and can be removed to avoid forgetting to add this prop. We can just use `class="link--transport"` instead.

2023-05-02 07:13 UTC, itemodahl approved these changes
LGTM

2023-05-03 07:06 UTC, lha047 requested changes
Good Job :D 

Have a look at icons.
Could you clear up the link stories too?

2023-05-03 07:06 UTC, lha047 commented on src/svelte/components/CardArticle.svelte
> +        class:link--transport={linkTypeTransport}>
I think you should remove the option. The cardArticle should always look the same

2023-05-05 07:29 UTC, petterkoding commented on src/scss/global/_links.scss
> +        border-bottom: var(--border-width-regular) solid var(--color-mt-beige);
Just realized this works for a single standalone link. If it's a list of links, then border-top and -bottom on each `<a>`  tag will create multiple lines between links. That's probably not what we want...

2023-05-05 08:54 UTC, lha047 requested changes
Nice :D

Left some more comments

2023-05-05 08:54 UTC, lha047 commented on stories/content/ProfessionalAdvice.stories.svelte
> +          linkTypeTransport={true}/>
Remove this?

2023-05-05 08:54 UTC, lha047 commented on stories/content/ProfessionalAdvice.stories.svelte
> +          linkTypeTransport={true}/>
Remove this?

2023-05-05 08:54 UTC, lha047 commented on src/scss/global/_links.scss
> +        transition: all ease-in-out 150ms;
Why do you need all here? isnt it just the padding-left that moves?

2023-05-11 06:01 UTC, lha047 approved these changes
Good job :D 

Fix comments before merging

2023-05-11 06:01 UTC, lha047 commented on stories/content/Task.stories.svelte
> +        linkTypeTransport={true}
```suggestion
```

2023-05-11 06:01 UTC, lha047 commented on src/scss/global/_links.scss
> +        transition: all ease-in-out 150ms;
```suggestion
        transition: padding-left ease-in-out 150ms;
```

2023-05-12 06:58 UTC, merged