MTP-1554: upgrade checkboxwithsubsets
Mattilsynet/designsystem pull request #840
Opened 2023-05-04 10:21 UTC by itemodahl

MTP-1554

2023-05-05 07:58 UTC, lha047 requested changes
Nice job :D

See comments

2023-05-05 07:58 UTC, lha047 commented on src/svelte/components/form/CheckboxWithSubSets.svelte
>      docCount: number
I think we need to make this optional

2023-05-05 07:58 UTC, lha047 commented on src/svelte/components/form/CheckboxWithSubSets.svelte
>            <label for={listItem.key}>{`${listItem.displayName} (${listItem.docCount})`}</label>
Dont show the docCount when its not present. Same for the other docCount

2023-05-08 10:56 UTC, itemodahl commented on src/svelte/components/form/CheckboxWithSubSets.svelte
>      docCount: number
What do you mean? It must be one of the two variations?

2023-05-08 10:57 UTC, itemodahl commented on src/svelte/components/form/CheckboxWithSubSets.svelte
>      docCount: number
Ah you mean docCount...

2023-05-08 13:16 UTC, merged