MTP-1278 Top task fix
Mattilsynet/designsystem pull request #874
Opened 2023-06-01 10:55 UTC by petterkoding

- Removed `word-break: break-word` where its been used.

- Added `word-break: break-word` to elements where the text overflows in _typography.scss

related issue:
https://mattilsynet.atlassian.net/jira/software/projects/MTP/boards/30?assignee=63fc1ae07c30bbd6b33d9682&selectedIssue=MTP-1275

2023-06-06 06:46 UTC, lha047 commented on src/scss/global/_typography.scss
> +.summary-list,
Can we make it so that we can have `<a><button><ul><ol><dl><p>` in this list? and not the specific classes?

2023-06-06 08:38 UTC, petterkoding commented on src/scss/global/_typography.scss
> +.summary-list,
see latest commit, for the `<a>` and `<button>`  I've used `:not` to avoid breaking the language, search and menu words in the header.

2023-06-09 08:04 UTC, lha047 requested changes
Looks nice :) 

Would prefere not to have exceptions on the word-beak rule. Have a look at my comment. Check if you can work with something like that

2023-06-09 08:04 UTC, lha047 commented on src/scss/global/_typography.scss
> +a:not(.button--link),
I would prefere not having exceptions on this. I think you can remove the `not()`-stuff if you change the `.button--link` a bit.
I tried to set button--link `min-width: max-content`. It seems to be ok. But on safari the header looks squashed. So I had to update `.header` in `_layout.scss` with `grid-template-columns: 1fr max-content max-content max-content;` then it seems to be ok.

2023-06-09 09:52 UTC, petterkoding commented on src/scss/global/_typography.scss
> +a:not(.button--link),
Agree, I also had that in mind after a while. Will take a look at your suggestions and go on from there

2023-06-12 07:45 UTC, lha047 approved these changes
Nice work :D

2023-06-12 08:02 UTC, merged