MTP-394 Fix Status li spacing and icon alignment
Mattilsynet/designsystem pull request #917
Opened 2023-08-08 09:40 UTC by petterkoding

To align the icon to center of the text without changing too much of the existing html or icon size properties, padding-top was added to the icon.

The  `calc( )` function uses the same line-height as the headings in the `_typography.scss`

For future work on icons, it would be easier if all icons had same width/height as the fonts size /lineheight.

2023-08-11 10:09 UTC, amundlindstol requested changes

2023-08-11 10:09 UTC, amundlindstol commented on mt-kit/core/css/src/components/_status.scss
> +    font-size: clamp(1.5869573348rem, 4.7816357022vw + 1rem, 2.368593037rem);
use variable

2023-08-11 10:33 UTC, petterkoding commented on mt-kit/core/css/src/components/_status.scss
> +        margin-top: var(--spacer-xxx-small);
Just trying to adjust spacing. Designer wants the spacing between each `li` to be smaller. Its currently using inherited styles for margin-top:  `--spacer-xx-small`

2023-08-11 14:08 UTC, tajakobsen approved these changes
Looks good. :+1:

2023-08-15 06:28 UTC, lha047 requested changes
Looks good :D 

See comment about Prettier

2023-08-15 06:28 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/content/Status.svelte
> +  <span class="{statusType} h2" data-testid="status-type"/>
Looks like there is somthing about spacing. There should be a space between `" />` at the end

2023-08-17 07:36 UTC, tajakobsen approved these changes
Looks good (again)

2023-08-17 08:12 UTC, merged