MTP-1666 mtp 1657 svelte part for a vise liste av regelverksprosesser pa en temaside
Mattilsynet/designsystem pull request #923
Opened 2023-08-24 14:03 UTC by petterkoding

2023-08-25 10:22 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/components/Published.svelte
> +  export let dtClass
Add default empty string so it doesn't put a undefined class in the string

2023-08-25 10:47 UTC, petterkoding commented on mt-kit/core/svelte/src/lib/svelte/components/Published.svelte
> +  export let dtClass
ok

2023-08-29 07:20 UTC, lha047 requested changes
See comment

2023-08-29 07:20 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/components/Published.svelte
> +  export let dtIcon = ''
On components i would only use class for the root component.
To target other elements use eg. dtClass. Dont think you need two variables for putting different classes. Would only use that when there is theming sizing etc. and that is a part of the class name. I would not use the same name incase someone later dont want the same styling

2023-08-30 08:37 UTC, lha047 approved these changes
Nice :D

2023-08-30 08:39 UTC, merged