MTP-1879 designjusteringer for lansering
Mattilsynet/designsystem pull request #969
Opened 2023-11-10 14:10 UTC by petterkoding

increase spacing between fieldset and error border

2023-11-13 06:44 UTC, lha047 commented on mt-kit/core/css/src/_theme.scss
> +$error-box-shadow-medium: 0 0 0 1.05rem var(--color-mt-background), 0 0 0 1.2rem var(--color-error);
```suggestion
$error-box-shadow-medium: 0 0 0 var(--spacer-xx-small) var(--color-mt-background),
  0 0 0 calc(var(--spacer-xx-small) + $border-width-large) var(--color-error);
```
Suggest using variables for this

2023-11-13 06:45 UTC, lha047 requested changes
Use variables for calculating spacing in box shaddow

2023-11-13 09:05 UTC, petterkoding commented on mt-kit/core/css/src/_theme.scss
> +$error-box-shadow-medium: 0 0 0 1.05rem var(--color-mt-background), 0 0 0 1.2rem var(--color-error);
@lha047  I dont think using the same values will work, as the borders are overlapping. The error border must be bigger to show underneath the "masking" border.

Making the second border  `--spacer-x-small` will make it look too big imo

2023-11-13 09:14 UTC, lha047 commented on mt-kit/core/css/src/_theme.scss
> +$error-box-shadow-medium: 0 0 0 1.05rem var(--color-mt-background), 0 0 0 1.2rem var(--color-error);
Thats why you calcualte the red border

2023-11-13 09:15 UTC, petterkoding commented on mt-kit/core/css/src/_theme.scss
> +$error-box-shadow-medium: 0 0 0 1.05rem var(--color-mt-background), 0 0 0 1.2rem var(--color-error);
Haha, my tired eyes just didnt see it! Sorry

2023-11-14 12:30 UTC, lha047 approved these changes
Nice :D

2023-11-15 10:41 UTC, merged