MTP-1862-utlisting-av-forsoksdyrsammendrag
Mattilsynet/designsystem pull request #995
Opened 2023-11-27 14:00 UTC by amundlindstol

2023-11-27 15:36 UTC, petterkoding commented
Tested in storybook. Looks good.

2023-11-28 12:06 UTC, lha047 requested changes
Looks good :) 

Just a few comments

2023-11-28 12:06 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/components/Table.svelte
> +  <caption class="m-t-m">
I think we should pass spacing to component. Might not always need it

2023-11-28 12:06 UTC, lha047 commented on mt-kit/core/svelte/src/lib/svelte/components/Table.svelte
> +<table class="mt-table responsive-table m-t-xxs {className}" id="table-{caption}" {style}>
`m-t-xxs` same as above

2023-11-28 13:46 UTC, lha047 approved these changes
Nice :D

2023-11-28 14:03 UTC, merged